---
title: "EDS 221 Day 3 Activities / Tasks"
format: html
editor: visual
---

## Day 3 Activities

https://allisonhorst.github.io/EDS_221_programming-essentials/activities/day_3_activities.html

```{r}
library(tidyverse)
library(here)
library(janitor)
```

## Task 1

```{r}
pm2_5 <- 48

if (pm2_5 < 100) {
  print("Low to moderate risk")
} else if (pm2_5 >= 100) {
  print("Unhealthy for sensitive groups")
} else if (pm2_5 >= 150) {
  print("Health risk present")
}
```

## Task 2

```{r}
species <- "blue whale"

if (str_detect(species, "whale")) {
  print("You found a whale!")
}
```

## Task 3

```{r}
base_burrito <- 6.50

main_ingredient <- "steak"

if (main_ingredient == "veggie") {
  print(base_burrito)
} else if (main_ingredient == "chicken") {
  print(base_burrito + 3.00)
} else if (main_ingredient == "steak") {
  print(base_burrito + 3.25)
}
```

# For loops

## Task 4

```{r}
fish <- c(8, 10, 12, 23)
# number represents counts of diff types of fish in a fish tank (goldfish, tetras, guppies, mollies)

for (i in seq_along(fish)) {
  prop_fish <- (fish[i] / sum(fish))
  print(prop_fish)
}
```

## Task 5

```{r}
for (i in seq_along(month.name)) {
  print(paste(month.name[i], "is month", i))
}

```

# 
